oneapi-spec:
  image: rscohn2/sphinx-tools
  script: "Clone support repos"
    - make clones
  script: "Build html"
    - make html
  script: "Build pdf"
    - make latexpdf
  script: "Build web site"
    - make public
  artifacts:
    paths:
    - public
