build:
  image: rscohn2/sphinx-tools
  stage: build
  script: 
    - make clones
    - make site
    - chmod 600 ${CI_PUBLISH_KEY_FILE}
    - make publish CI_PUBLISH_DIR=`echo ${CI_COMMIT_REF_NAME}|tr / _` CI_PUBLISH_KEY_FILE=${CI_PUBLISH_KEY_FILE}
  artifacts:
    paths:
      - site/

publish:
  script:
    - pip install awscli
  rules:
    - if: '$CI_COMMIT_REF_NAME == publish'
      when: always