build:
  image: rscohn2/oneapi-spec
  stage: build
  script:
    - export no_proxy=.intel.com
    - export NO_PROXY=$no_proxy
    - export http_proxy=http://proxy-us.intel.com:911
    - export https_proxy=$http_proxy
    - python3 scripts/oneapi.py --branch $CI_COMMIT_REF_NAME ci
