build:
  image: rscohn2/sphinx-tools
  stage: build
  script: Clone support repos
    - make clones
  script: Build html
    - make html
  script: Build pdf
    - make latexpdf
  script: Build web site
    - make public

deploy:
  stage: deploy
  script:
    - ls
  only:
    - master
