# SPDX-FileCopyrightText: 2019-2022 Intel Corporation
#
# SPDX-License-Identifier: MIT

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/sphinx-doc/sphinx:5.3.0
    steps:
    - uses: actions/checkout@v2
    - name: Install prerequisites
      run: |
          pip install sphinx-book-theme pre-commit
          apt install -y git
    - name: Checks
      run: |
          pre-commit run --all
    - name: Build
      run: |
        make html
    - name: Archive build directory
      uses: actions/upload-artifact@v3
      with:
          name: _build
          path: _build
    - name: Checkout gh-pages
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: actions/checkout@v3
      with:
        ref: gh-pages
        path: gh-pages
    - name: Publish to github pages
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |
          cd gh-pages
          rm -rf release-notes
          cp -r _build/html release-notes
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit --reset-author --amend -m "Update from github actions"
          git push --force origin gh-pages
