# SPDX-FileCopyrightText: 2019-2020 Intel Corporation
#
# SPDX-License-Identifier: MIT

on:
  push:
    branches:
    - 'main'
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install ubuntu prerequisites
      run: |
        sudo apt update -qq
        xargs -a ubuntu-packages.txt sudo apt install -qq
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    - name: Install python prerequisites
      run: pip install --quiet -r requirements.txt
    - name: Checks
      run: |
        pre-commit run --all
        mkdir -p build/reuse
        # ignore fail for reuse
        reuse lint > build/reuse/lint.txt || true
    - name: Build html
      env:
        ONEAPI_DRAFT: true
      run: |
        python scripts/oneapi.py -W html
    - name: Build pdf
      env:
        ONEAPI_DRAFT: true
      run: |
        python scripts/oneapi.py -W latexpdf
    #- name: Archive build directory
    #  uses: actions/upload-artifact@v3
    #  with:
    #    name: build
    #    path: build
    - name: Checkout gh-pages
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: actions/checkout@v3
      with:
        ref: gh-pages
        path: gh-pages
    - name: Publish to github pages
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |
        cd gh-pages
        touch .nojekyll
        rm -rf spec
        mkdir spec
        cd spec
        cp -r ../../build/html/* .
        cp ../../build/latex/*.pdf .
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit --reset-author --amend -m "Update from github actions"
        git push --force origin gh-pages
